services:
  go-db:
    container_name: go-db
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - ${MONGO_SERVER_PORT}:${MONGO_SERVER_PORT}
    volumes:
      - ./mongodb-data:/data/db
    logging:
      driver: none
    env_file:
      - .env
    networks:
      - go-server

networks:
  go-server:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
